apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speed-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
    periodSeconds: 1
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    inbound:
      rules:
        - application: spaghet
        - application: speed-async
        - application: spennende
        - application: spedisjon-async
        - application: sparkel-gosys
        - application: sparkel-norg
        - application: sparkel-personinfo
        - application: sporbar
        - application: spre-gosys
        - application: spre-styringsinfo
        - application: vedtaksfeed
        {{#each accessPolicy.inbound.rules }}
        - application: {{application}}
        {{/each }}
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: {{pdlHostname}}
  valkey:
    - instance: mellomlager
      access: readwrite
  ingresses:
    {{#each ingresses }}
    - "{{this}}"
    {{/each}}
  env:
    - name: PDL_URL
      value: https://{{pdlHostname}}/graphql
    - name: PDL_SCOPE
      value: {{pdlScope}}
