apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speed-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    inbound:
      rules:
        - application: speed-async
        - application: spennende
        - application: spedisjon
    outbound:
      external:
        - host: {{pdlHostname}}
  redis:
    - instance: mellomlager
      access: readwrite
  ingresses:
    {{#each ingresses }}
    - "{{this}}"
    {{/each}}
  env:
    - name: PDL_URL
      value: https://{{pdlHostname}}/graphql
    - name: PDL_SCOPE
      value: {{pdlScope}}
