apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speed-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: speed-async
  redis:
    - instance: mellomlager
      access: readwrite
  ingresses:
    - {{ingress}}
