[versions]
tbdLibs = "20261002.1227"
sykepengerGradlePlugins = "20261001.1830"

[libraries]
avro = "org.apache.avro:avro:1.12.2"
jedis = "redis.clients:jedis:8.0.1"
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
logback-classic = "ch.qos.logback:logback-classic:1.6.4"
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:9.0"
mockk = "io.mockk:mockk:1.14.11"
rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026091610031789545782"
tbdLibs-azureTokenClientDefault = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbdLibs" }
tbdLibs-mockHttpClient = { module = "com.github.navikt.tbd-libs:mock-http-client", version.ref = "tbdLibs" }
tbdLibs-naisfulApp = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbdLibs" }
tbdLibs-naisfulTestApp = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbdLibs" }
tbdLibs-rapidsAndRiversTest = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbdLibs" }
tbdLibs-speedClient = { module = "com.github.navikt.tbd-libs:speed-client", version.ref = "tbdLibs" }

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
sykepenger-root = { id = "no.nav.sykepenger.root", version.ref = "sykepengerGradlePlugins" }
